// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/monit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsAccessible   bool                   `protobuf:"varint,3,opt,name=is_accessible,json=isAccessible,proto3" json:"is_accessible,omitempty"`
	StatusCode     int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,8,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Url            string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ErrorReason    string                 `protobuf:"bytes,6,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_proto_monit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_proto_monit_proto_rawDescGZIP(), []int{0}
}

func (x *CheckResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CheckResult) GetIsAccessible() bool {
	if x != nil {
		return x.IsAccessible
	}
	return false
}

func (x *CheckResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CheckResult) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CheckResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CheckResult) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *CheckResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ResultSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CheckResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultSet) Reset() {
	*x = ResultSet{}
	mi := &file_proto_monit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSet) ProtoMessage() {}

func (x *ResultSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSet.ProtoReflect.Descriptor instead.
func (*ResultSet) Descriptor() ([]byte, []int) {
	return file_proto_monit_proto_rawDescGZIP(), []int{1}
}

func (x *ResultSet) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_monit_proto protoreflect.FileDescriptor

const file_proto_monit_proto_rawDesc = "" +
	"\n" +
	"\x11proto/monit.proto\x12\amonitor\"\xf5\x01\n" +
	"\vCheckResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\ris_accessible\x18\x03 \x01(\bR\fisAccessible\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x10response_time_ms\x18\b \x01(\x03R\x0eresponseTimeMs\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12!\n" +
	"\ferror_reason\x18\x06 \x01(\tR\verrorReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\";\n" +
	"\tResultSet\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.monitor.CheckResultR\aresultsB\tZ\a./protob\x06proto3"

var (
	file_proto_monit_proto_rawDescOnce sync.Once
	file_proto_monit_proto_rawDescData []byte
)

func file_proto_monit_proto_rawDescGZIP() []byte {
	file_proto_monit_proto_rawDescOnce.Do(func() {
		file_proto_monit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monit_proto_rawDesc), len(file_proto_monit_proto_rawDesc)))
	})
	return file_proto_monit_proto_rawDescData
}

var file_proto_monit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_monit_proto_goTypes = []any{
	(*CheckResult)(nil), // 0: monitor.CheckResult
	(*ResultSet)(nil),   // 1: monitor.ResultSet
}
var file_proto_monit_proto_depIdxs = []int32{
	0, // 0: monitor.ResultSet.results:type_name -> monitor.CheckResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_monit_proto_init() }
func file_proto_monit_proto_init() {
	if File_proto_monit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monit_proto_rawDesc), len(file_proto_monit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_monit_proto_goTypes,
		DependencyIndexes: file_proto_monit_proto_depIdxs,
		MessageInfos:      file_proto_monit_proto_msgTypes,
	}.Build()
	File_proto_monit_proto = out.File
	file_proto_monit_proto_goTypes = nil
	file_proto_monit_proto_depIdxs = nil
}
